services:
    bot:
        container_name: elysia-temp-draft-bot
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            -   NODE_ENV=production
    postgres:
        container_name: elysia-temp-draft-postgres
        image: postgres:latest
        restart: unless-stopped
        environment:
            -   POSTGRES_USER=elysia-temp-draft
            -   POSTGRES_PASSWORD=31d82f6964d96a4c6cd1247c
            -   POSTGRES_DB=elysia-temp-draft
        volumes:
            -   postgres_data:/var/lib/postgresql/data
    redis:
        container_name: elysia-temp-draft-redis
        image: redis:latest
        command: [redis-server, --maxmemory-policy, noeviction]
        restart: unless-stopped
        volumes:
            -   redis_data:/data
volumes:
    postgres_data:
    redis_data:

networks:
    default: {}
